version: '3.1'

services:

  api:
    build: 
      context: ./api
    depends_on: 
      - redis
    container_name: flask-api
    networks:
      - default
    ports:
      - 8080:8080
    networks:
      - db_network
    expose:
      - 8080 
      
  db:
    image: postgis/postgis
    restart: always
    #TODO adicionar dados a partir de uma enviroment
    environment:
      POSTGRES_PASSWORD: 'postgres_password'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      # - pgdata:/var/lib/postgresql/data
    ports:
      - 5405:5432
    networks:
      - db_network

  redis:
    image: redis:6.2.6-alpine
    ports:
      - "6379:6379"
    networks:
      - db_network
    volumes:
      - ./redis:/redis

  worker:
    build: 
      context: ./worker
    depends_on: 
      - db
      - redis
    networks:
      - default
    environment:
      POSTGRES_PASSWORD: 'postgres_password'
    ports:
      - 8081:8080
    networks:
      - db_network
    # expose:
    #   - 8081 
      

networks:
  db_network:
    driver: bridge

volumes:
  pgdata:
    external: false