version: '3.1'

services:

  api:
    build: 
      context: ./api
    depends_on: 
      - db
    networks:
      - default
    environment:
      POSTGRES_PASSWORD: 'postgres_password'
    ports:
      - 8080:8080
    networks:
      - db_network
    expose:
      - 8080 
      
  db:
    image: postgis/postgis
    restart: always
    #TODO adicionar dados a partir de uma enviroment
    environment:
      POSTGRES_PASSWORD: 'postgres_password'
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      # - pgdata:/var/lib/postgresql/data
    ports:
      - 5405:5432
    networks:
      - db_network


networks:
  db_network:
    driver: bridge

volumes:
  pgdata:
    external: false