version: '3.1'

services:

  api:
    build: .
    depends_on: 
      - db
    restart: always
    networks:
      - default
    environment:
      - APP_NAME=TRIPS_API
    ports:
      - 8080:8080
    expose:
      - 8080 
    # volumes:
    #   - ./app:/usr/src/app/app
      
  db:
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_DB: test
      POSTGRES_PASSWORD: test
    networks:
      - default
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5405:5432

volumes:
  pgdata:
    external: false